spellername = "Bashkir"
spellerversion = "0.1.1"

# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Bashkir spellchecker"
ba = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Bashkir, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
ba = "TRANSLATE: A spellchecker for Bashkir, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.ba"

[windows]
system_product_code = "{1963B800-C488-475F-B7EB-39C91D3B1D7E}_is1"
legacy_product_codes = [
    { value = "77ACE14F-C060-4774-974A-1CF1B83CA872", kind = "nsis" },
    { value = "573AD305-E862-49D4-ADDB-1B8E7BC690E0", kind = "nsis" }
]
