name = "Bashkir"
version = "0.1.0"

[macos]
system_pkg_id = "no.divvun.MacDivvun.ba"

[windows]
system_product_code = "77ACE14F-C060-4774-974A-1CF1B83CA872"
msoffice_product_code = "573AD305-E862-49D4-ADDB-1B8E7BC690E0"
