template = "https://github.com/giellalt/template-lang-und"
rev_id = 334
template_sha = "295433261311db06974764ace81fbb35d1f5ac28"

[replacements]
__GLOTTOLOG_ID__ = "bash1264"
__REPO__ = "lang-bak"
__UND2C__ = "ba"
__UNDEFINED__ = "Bashkir"
__UND__ = "bak"
