[package]
name = "bak"
human_name = "Bashkir"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.bak]
filename = "ba-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-bak"
platform = "windows"
uuid = "77ACE14F-C060-4774-974A-1CF1B83CA872"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.ba"
package = "speller-bak"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-bak-mso"
platform = "windows"
uuid = "573AD305-E862-49D4-ADDB-1B8E7BC690E0"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-bak"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
